# Generated by Django 4.2.5 on 2023-10-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPARTAMENTO', models.CharField(max_length=100)),
                ('MUNICIPIO', models.CharField(max_length=100)),
                ('CODIGO_DANE', models.CharField(max_length=100)),
                ('ARMAS_MEDIOS', models.CharField(max_length=100)),
                ('FECHA_HECHO', models.CharField(max_length=100)),
                ('GENERO', models.CharField(max_length=100)),
                ('GRUPO_ETARIO', models.CharField(max_length=100)),
                ('CANTIDAD', models.CharField(max_length=100)),
            ],
        ),
    ]
