# Generated by Django 4.2.5 on 2023-10-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViolenciaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='CANTIDAD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dane',
            name='CODIGO_DANE',
            field=models.IntegerField(),
        ),
    ]
