# Generated by Django 4.2.5 on 2023-10-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViolenciaApp', '0002_alter_dane_cantidad_alter_dane_codigo_dane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='CODIGO_DANE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dane',
            name='FECHA_HECHO',
            field=models.DateField(),
        ),
    ]
