# Generated by Django 4.2.5 on 2023-10-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViolenciaApp', '0003_alter_dane_codigo_dane_alter_dane_fecha_hecho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geojason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('crs', models.JSONField()),
                ('features', models.JSONField()),
            ],
        ),
    ]
